import './theme.css';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import { PropsWithChildren } from 'react';

const font = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
	return (
		<html lang="en">
			<body className={font.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
