import './theme.css';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import { PropsWithChildren } from 'react';
import { fetchGlobalContent } from '@/api-client/api-client';

const [error, global] = await fetchGlobalContent();

if (error || !global) {
	const _error = error instanceof Error
		? error
		: new Error('Content could not be found.');
	console.error(_error);
};

const font = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
	return (
		<html lang="en">
			<head>
				<script type="application/json" id="GlobalContent" dangerouslySetInnerHTML={{
					__html: JSON.stringify({ global }),
				}}></script>
			</head>
			<body className={font.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
